### ISSUE TITLE
Invalid end date in parsed TAF forecast

### ISSUE THREAD

**Issue by SkySails** [aeharding/metar-taf-parser#56]
First of all, thanks a lot for this excellent library! It works really well.
I stumbled upon this issue (?) though and would like to know if it is intended and/or known.

When parsing the following TAF on the demo page:

```
TAF ESGG 260830Z 2609/2709 02009KT 3000 BR BKN003
BECMG 2609/2611 9999 NSW FEW015
```

I get the following result. Shouldn't the start/end dates of the root object match up with the ones in the first forecast?
Notice how in the first forecast entry, the start and end dates are identical.

![metar-taf-parser 01-27](https://user-images.githubusercontent.com/46646495/214971595-6ae3cf02-224c-41f7-a50e-d9882c67fa3a.png)

The issue goes away if I remove the second line of the provided TAF:

![metar-taf-parser 01-27](https://user-images.githubusercontent.com/46646495/214971883-8178d900-3f15-47fb-9570-8989f019f376.png)

It seems like I can safely fall back to the "root" start/end dates for the first entry, just wanted to know if this was intentional!

**Comment by aeharding** [comment]
Hi there!

Thanks for the kind words, and opening the issue!

So I've looked at this TAF, and I'm going to attempt to explain when I believe is happening.

So if you notice, the start of the BECMG is 2609Z (`2609/2611`). However, that also happens to be the start of the validity period of the TAF -  `2609/2709`.

So because the start of the BECMG is the exact same time as the start of the TAF, the initial conditions essentially have a validity period of nothing (2609Z-2609Z).

**Comment by aeharding** [comment]
(sorry, accidentally pressed submit. continuing my post...)

But a validity period of nothing might not be that helpful(?), and the forecast abstraction (parseTAFAsForecast) is supposed to be a nice, clean API for people to use. So, I could potentially filter out the initial conditions if the validity period is zero, so the forecast array will only have the BECMG.

But again, it might be nice for people to know when the initial conditions were (and what they're BECMG) - even if the validity period is 0.

What are your thoughts?

**Comment by aeharding** [comment]
I could potentially make a configurable option as well.

**Comment by SkySails** [comment]
Sorry for the delayed reply, must have missed the notifications!

> So if you notice, the start of the BECMG is 2609Z (`2609/2611`). However, that also happens to be the start of the validity period of the TAF - `2609/2709`.
> 
> So because the start of the BECMG is the exact same time as the start of the TAF, the initial conditions essentially have a validity period of nothing (2609Z-2609Z).

I see what you mean. However, I do not fully understand the reasoning behind this. I'll try to elaborate a bit more!

Aren't the initial conditions still very much relevant in the case of a `BECMG` group? This group describes a gradual change that will take place over a prolonged period of time but will be the prevailing weather once that transition is complete. Wouldn't the initial conditions be vital to create a perception of what kind of transition is about to take place? Is the weather worsening or getting better? We don't know - we only know what it is _going to look like_ at the end of the specified time interval.

The way I see it, for the particular example mentioned here, there is a _transition_ from one type of weather to another that starts _immediately_ when the forecast was issued. There can't be a transition if only the end state is known.

These are my thoughts. Perhaps I am overthinking this or have missed something!

**Comment by aeharding** [comment]
I agree with all of what you said. It's definitely a weird edge case with no straightforward solution.

Also keep in mind that BECMG trends are hydrated with the context of previous trends. So while you're right, BECMG really is supposed to show a gradual change to certain conditions, metar-taf-parser is already making certain assumptions specifically for the forecast abstraction. So maybe it would be OK to just filter out those zero-length validity periods (since relevant data is propagated to the BECMG).

**Comment by SkySails** [comment]
> So maybe it would be OK to just filter out those zero-length validity periods (since relevant data is propagated to the BECMG).

Yes, perhaps you're right. I _think_ I would prefer filtering it out myself to avoid the potential confusion caused by an "expected" forecast just disappearing - but a 0ms validity period is obviously not that intuitive either. Perhaps a configurable option to exclude such forecasts (like you already mentioned) would be the best bet!

**Comment by aeharding** [comment]
Oh another thought - the forecast abstraction is based on the parsing of TAFs here, more or less:

https://www.aviationweather.gov/taf/data?ids=kmsn&format=decoded&metars=off&layout=on

Unfortunately you cannot enter arbitrary data, you have to enter an ICAO ID to see the decided data.

So if you see a TAF like this again in the wild, enter the airport ICAO and screenshot the page of the decided TAF from that site and post it here. :)

**Comment by SkySails** [comment]
I have not seen one in the wild yet, but I am not actively monitoring this either. Let's close this for now, and I'll re-open it if I find a similar report!
