### ISSUE TITLE
Cannot parse where visibility is directional

### ISSUE THREAD

**Issue by drmrbrewer** [aeharding/metar-taf-parser#62]
According to [this page](https://metar-taf.com/explanation#visibility):

> Visibility can also be listed per direction. `1500SW 2000NE` means the visibility to the southwest is 1500 meters and 2000 meters to the northeast.

It seems that this isn't accounted for by this parser... as per [this example](https://aeharding.github.io/metar-taf-parser/metar?input=CYVR+301300Z+09006KT+1500SW+2000NE+FEW055+FEW120+M04%2FM06+A3049+RMK+SC1AC1+SC+TR+SLP327) it gives the following error:

`UnexpectedParseError: container.visibility not instantiated`

**Comment by aeharding** [comment]
Based on the following, page 25-28, it appears as if the directional visibility will always accompany a primary visibility.

https://www.vaisala.com/sites/default/files/documents/Vaisala%20unmanned%20automatic%20weather%20observations%20at%20airports.pdf

> The minimum visibility is also included when the visibility in one direction, which is not the prevailing visibility, is less than 1,500 meters or less than 50% of the prevailing visibility and less than 5000 meters. A direction is also added if possible, as N, NE, E, SE, S, SW, W and NW. If the direction cannot be determined like in AUTO metar, NDV (No directional visibility) keyword can be used.

It seems like a visibility with a direction attached will always have a prevailing visibility (without a specific direction). For example

> 3200 1200SW

Here's you example, but with the above visibility string, working correctly:

https://aeharding.github.io/metar-taf-parser/metar?input=CYVR+301300Z+09006KT+3200+1200SW+2000NE+FEW055+FEW120+M04%2FM06+A3049+RMK+SC1AC1+SC+TR+SLP327

It seems like it may be possible (?) to have more than one minimum visibility directions, but I'm not sure.

Do you have a specific example of a real METAR with a direction but without a prevailing visibility?

**Comment by drmrbrewer** [comment]
You may well be right, but it's frustratingly difficult to find a definitive resource.

[This reference](http://www.bom.gov.au/aviation/data/education/taf-reference-card.pdf) backs up your theory:

![image](https://user-images.githubusercontent.com/9009792/215598152-8546f5e8-95c2-479d-b3d7-2155431395c0.png)

But [this source](http://woodair.net/aviation/metar.htm) only refers to "two groups" (not in addition to a prevailing group):

![image](https://user-images.githubusercontent.com/9009792/215598427-9bf50d7a-9afd-445f-931c-db83415d9864.png)

And then [this source](https://www.metoffice.gov.uk/binaries/content/assets/metofficegovuk/pdf/services/transport/aviation/helibrief/helibrief_help_-_aerodrome_actual_weather_-_metar_decode.pdf) again suggests there is a prevailing visibility followed by a directional visibility:

![image](https://user-images.githubusercontent.com/9009792/215599328-209d6cd6-6636-4bc7-a6b6-a5c44d35b7ad.png)

On balance (and based on the "officialness" of the above sources) it does seem that you're correct that a directional visibility should follow a non-directional visibility.

Happy to close this if you are.

**Comment by aeharding** [comment]
Sounds good! Please let me know if you find anything weird like this in a real METAR and I will reopen this.
