### ISSUE TITLE
Cannot parse TAF with station beginning "FM"

### ISSUE THREAD

**Issue by mattj65817** [aeharding/metar-taf-parser#67]
`FM` is always assumed to be a from-group in the tokenization process. The end result of this is that TAFs (and probably METARs, though I haven't checked yet) beginning with "FM" cannot be parsed.

This can be fixed by updating the pattern in extractLinesTokens(tafCode):

From
> .replace(/\s(?=PROB\d{2}\s(?=TEMPO|INTER)|TEMPO|INTER|BECMG|FM|PROB)/g, "\n")

To
> .replace(/\s(?=PROB\d{2}\s(?=TEMPO|INTER)|TEMPO|INTER|BECMG|FM(?![A-Z])|PROB)/g, "\n")

I'm just digging into this now, I'm looking into a few other failures. Want a pull request?

**Comment by mattj65817** [comment]
...using `(?![A-Z]{2})` for the lookahead may be better, since a station ID will always be 4 characters in total.

**Comment by aeharding** [comment]
Pull request welcome, just make sure it include tests! :) Thanks!
