### ISSUE TITLE
Cannot parse "PART x OF y" in NOAA TAF cycle entries

### ISSUE THREAD

**Issue by mattj65817** [aeharding/metar-taf-parser#68]
The NOAA TAF cycles contain entries which begin with `PART x OF y`, for example, `PART 1 OF 2 TAF KXYZ...`. There is no provision for parsing or skipping this. If you'd like, I could take a stab at adding support for it. If it *is* supported, you'd probably want to note the partial in the parsed TAF output.

I've not written any code for this yet since you could go either way on it. It's not technically part of the TAF, so perhaps you don't want to parse it at all, but it *does* appear in the cycle files, so anybody using the library to parse cycle files would need to handle it in a preprocess step.

**Comment by aeharding** [comment]
Hi there!

Could you provide more information on this? Any documentation or common sources that include TAF in this form?

thanks.

**Comment by mattj65817** [comment]
> Hi there!
> 
> Could you provide more information on this? Any documentation or common sources that include TAF in this form?
> 
> thanks.

Sure, this will be somewhat slippery since the NOAA cycles rotate every 24 hours, but they always seem to contain a few of these. For example, see the current [00Z-06Z](https://tgftp.nws.noaa.gov/data/forecasts/taf/cycles/00Z.TXT) cycle and search for something like `PART 2 OF 2`.

Here is one example for durability's sake:

```
2023/05/08 00:00 
PART 2 OF 2 TAF SBGL 082150Z 0900/1006 09007KT CAVOK TN21/0909Z TX30/0917Z 
      BECMG 0903/0905 34005KT SCT020 PROB40 0909/0912 4000 BR SCT010 BKN020 
      BECMG 0912/0914 01005KT FEW023 
      BECMG 0917/0919 23017KT SCT020 
      BECMG 0921/0923 27008KT BKN025 
      BECMG 1004/1006 5000 BR BKN010 
      RMK PHP
```

My notes on this:
* I don't think I've ever seen multiple parts of the same sequence (`PART 1 OF 2 TAF KXYZ...` and `PART 2 OF 2 TAF KXYZ...`) in the *same* cycle file. I've never looked very hard for it, though, as I've never seen this in US TAFs.
* I don't see how this could ever be of interest to anyone unless they are parsing *full* cycles. It's easy enough to parse it out in a preprocess step if you just want the weather for a station.

I think the value in handling this is low, I only mention it because it's one more example of garbage in a TAF you *might* choose to tolerate for sake of comprehensiveness if nothing else.

**Comment by aeharding** [comment]
Interesting. At very least, it might be nice to detect this and throw a custom error so that people can catch/there is no unexpected behavior.

Thoughts? PRs welcome of course, otherwise, I'll look at this soon enough.
