### ISSUE TITLE
support node

### ISSUE THREAD

**Issue by SummerZYQ** [aeharding/metar-taf-parser#72]
I'am use it in node for api server, but can't use es module.
can out UMD for support both node and browser ?

```
Error [ERR_REQUIRE_ESM]: require() of ES Module D:\**\node_modules\.pnpm\metar-taf-parser@8.0.2\node_modules\metar-taf-parser\metar-taf-parser.js from D:\**\src\app.ts not supported.
```

**Comment by aeharding** [comment]
Hi there! node.js is supported, but only as an esm module. This was an intentional choice for this project.

There's more information here, that may be helpful! https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by SummerZYQ** [comment]
> Hi there! node.js is supported, but only as an esm module. This was an intentional choice for this project.
> 
> There's more information here, that may be helpful! https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c



> Hi there! node.js is supported, but only as an esm module. This was an intentional choice for this project.
> 
> There's more information here, that may be helpful! https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

thanks for you reply. I'm to see

> Hi there! node.js is supported, but only as an esm module. This was an intentional choice for this project.
> 
> There's more information here, that may be helpful! https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

thanks

**Comment by SummerZYQ** [comment]
> Hi there! node.js is supported, but only as an esm module. This was an intentional choice for this project.
> 
> There's more information here, that may be helpful! https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

thanks
