### ISSUE TITLE
CommandExecutionError: 0 not found in /,1,2,5,9

### ISSUE THREAD

**Issue by daniluk4000** [aeharding/metar-taf-parser#96]
Gettings this error when trying to parse this METAR

UUWW 151030Z 34002MPS CAVOK 14/02 Q1026 R01/000070 NOSIG

Also reproducable in your demo

**Comment by aeharding** [comment]
Hi! This is because `R01/000070` is invalid. However it should probably not fail completely.

**Comment by aeharding** [comment]
Can you review #97 and let me know if that would work for you? Thanks!

**Comment by daniluk4000** [comment]
> Can you review #97 and let me know if that would work for you? Thanks!

I trust tests :)

Thank you for this quick fix!

**Comment by aeharding** [comment]
Should be working on 9.0.1! Thanks for reporting.

https://aeharding.github.io/metar-taf-parser/metar?input=UUWW+151030Z+34002MPS+CAVOK+14%2F02+Q1026+R01%2F000070+NOSIG
