### ISSUE TITLE
i18n doesn't work

### ISSUE THREAD

**Issue by windbullet** [aeharding/metar-taf-parser#98]
my code:
![image](https://github.com/aeharding/metar-taf-parser/assets/47932422/da2b57fe-0ab0-4044-9fec-29fabe72dcf3)
return:
![image](https://github.com/aeharding/metar-taf-parser/assets/47932422/cadb9eae-4603-47fe-a7c7-1147aad1630f)

**Comment by aeharding** [comment]
Hi! I am a bit confused by your screenshots. Localization is only done for remarks, which is an empty array in your screenshot.

Localization of weather conditions/clouds/visibility etc is left to the user.

Let me know if that clears things up!

**Comment by windbullet** [comment]
I thought those would be localized too, sorry!
But is there a way to localize weather conditions/clouds/visibility etc as well?
